specwww 866
simonsfoundation/spectrum-autism-prevalence-map pull request #28
Opened 2023-01-26 16:15 UTC by yjfnyc

2023-01-26 21:50 UTC, myicicle requested changes
Could you please update the README.md to reflect the current process? Thanks!

2023-01-27 15:43 UTC, myicicle requested changes
Do you need to remove 'income level' and 'education level', as well?
<img width="495" alt="Screenshot 2023-01-27 at 10 42 27 AM" src="https://user-images.githubusercontent.com/7129258/215127268-ce51e24b-6417-44b8-a2f1-949bf94de86e.png">

2023-01-27 17:11 UTC, myicicle approved these changes
I understand that you want to leave the logic for income and education and just want to hide them, but I would probably also remove JS for these like spectrum-autism-prevalence-map/spectrum/autism_prevalence_map/static/autism_prevalence_map/js/joint.js, line 156:     $("#meanincomeofparticipants").on("change", function(e) {...})
But it's good to merge without removing them.

2023-01-27 17:19 UTC, yjfnyc commented
> I understand that you want to leave the logic for income and education and just want to hide them, but I would probably also remove JS for these like spectrum-autism-prevalence-map/spectrum/autism_prevalence_map/static/autism_prevalence_map/js/joint.js, line 156: $("#meanincomeofparticipants").on("change", function(e) {...}) But it's good to merge without removing them.

Thanks for the great review.

2023-01-27 17:19 UTC, merged