ttwww-336: initial work for upgrade django
simonsfoundation/spectrum-autism-prevalence-map pull request #36
Opened 2024-09-10 13:56 UTC by yjfnyc

2024-11-12 18:32 UTC, roarmeow approved these changes
This looks good; it took me so long it might be a little out of date, but everything works as expected. Thanks for your patience! :shipit:

2024-11-13 15:57 UTC, mdmallardi commented on requirements.txt
> +Django==3.2
This is absolutely not 'off topic'

Why are we only moving to Django 3.2.0?  That's quite old at this point, and as Prisma is pointing out, has several security holes.  Please look at using at least 3.2.25 to use the latest 3.2.x series.  Thanks!

2024-11-13 15:59 UTC, mdmallardi requested changes
Please make certain to use the latest release in the package series' you are using, to ensure that we are not leaving security holes open needlessly.  Thanks!

2025-09-18 15:56 UTC, yjfnyc commented
Close this because this was incorporated into other [PR](https://simonsfoundation.atlassian.net/browse/TTWWW-336?focusedCommentId=118371).

2025-09-18 15:56 UTC, closed without merging